<?php
// Centralized PHP Static Mock Dataset for Wisetrack

$currentUser = [
    "name" => "Yogesh Kumar",
    "email" => "yogesh.k@wisetrack.com",
    "role" => "Super / Project Admin",
    "avatar" => "YK",
    "department" => "Engineering PMO"
];

$resorts = [
    [
        "id" => "RES-GOA-01",
        "name" => "Grand Oasis Resort & Spa",
        "location" => "Candolim Beach, Goa",
        "code" => "GOA-OASIS",
        "gm" => "Vikramaditya Roy",
        "budget" => "₹48.50 Cr",
        "spent" => "₹34.20 Cr",
        "progress" => 76,
        "status" => "On Track",
        "statusBadge" => "green",
        "totalProjects" => 6,
        "targetDate" => "30 Dec 2026",
        "desc" => "5-Star beachfront luxury luxury resort development featuring 180 keys, infinity pool, luxury villas, and central MEP plant."
    ],
    [
        "id" => "RES-JAI-02",
        "name" => "Royal Heritage Palace & Villas",
        "location" => "Amer Road, Jaipur",
        "code" => "JAI-HERIT",
        "gm" => "Meenakshi Rathore",
        "budget" => "₹36.20 Cr",
        "spent" => "₹21.40 Cr",
        "progress" => 58,
        "status" => "At Risk",
        "statusBadge" => "amber",
        "totalProjects" => 4,
        "targetDate" => "15 Mar 2027",
        "desc" => "Heritage palace renovation and luxury tented villa expansion preserving Rajput architecture with modern MEP automation."
    ],
    [
        "id" => "RES-MAN-03",
        "name" => "Pine Valley Mountain Resort",
        "location" => "Solang Valley, Manali",
        "code" => "MAN-PINE",
        "gm" => "Karan Grover",
        "budget" => "₹24.80 Cr",
        "spent" => "₹20.30 Cr",
        "progress" => 84,
        "status" => "On Track",
        "statusBadge" => "green",
        "totalProjects" => 3,
        "targetDate" => "15 Nov 2026",
        "desc" => "High-altitude eco-chalets, geothermal HVAC heating network and glass-domed observatory restaurant."
    ],
    [
        "id" => "RES-KOV-04",
        "name" => "Azure Sands Beach Retreat",
        "location" => "Lighthouse Beach, Kovalam",
        "code" => "KOV-AZURE",
        "gm" => "Sangeeta Nair",
        "budget" => "₹19.40 Cr",
        "spent" => "₹9.80 Cr",
        "progress" => 42,
        "status" => "Delayed",
        "statusBadge" => "red",
        "totalProjects" => 3,
        "targetDate" => "28 Feb 2027",
        "desc" => "Ayurvedic wellness sanctuary featuring cliffside infinity pool and sustainable timber suites."
    ]
];

$projects = [
    [
        "id" => "PRJ-01",
        "resortId" => "RES-GOA-01",
        "resortName" => "Grand Oasis Resort & Spa",
        "parentId" => null,
        "level" => 1,
        "name" => "Main Resort Building Phase-1 (Civil & Structure)",
        "code" => "GR-CIV-001",
        "discipline" => "Civil Structure",
        "owner" => "Amit Verma",
        "budget" => "₹16.50 Cr",
        "spent" => "₹13.20 Cr",
        "progress" => 80,
        "health" => "On Track",
        "healthBadge" => "green",
        "startDate" => "10 Jan 2026",
        "endDate" => "30 Nov 2026",
        "childrenCount" => 2,
        "desc" => "Primary hotel block superstructure, RCC frame, roof waterproofing and core masonry."
    ],
    [
        "id" => "PRJ-01-SUB1",
        "resortId" => "RES-GOA-01",
        "resortName" => "Grand Oasis Resort & Spa",
        "parentId" => "PRJ-01",
        "level" => 2,
        "name" => "Block A Guest Wing Superstructure",
        "code" => "GR-CIV-001-A",
        "discipline" => "Civil Structure",
        "owner" => "Amit Verma",
        "budget" => "₹9.20 Cr",
        "spent" => "₹7.80 Cr",
        "progress" => 85,
        "health" => "On Track",
        "healthBadge" => "green",
        "startDate" => "10 Jan 2026",
        "endDate" => "15 Oct 2026",
        "childrenCount" => 2,
        "desc" => "G+4 floor RCC slab casting, brickwork partition and waterproofing."
    ],
    [
        "id" => "PRJ-01-SUB1-T1",
        "resortId" => "RES-GOA-01",
        "resortName" => "Grand Oasis Resort & Spa",
        "parentId" => "PRJ-01-SUB1",
        "level" => 3,
        "name" => "Floor 1-4 RCC Slab Casting & Columns",
        "code" => "GR-CIV-001-A-WP1",
        "discipline" => "Civil Structure",
        "owner" => "Site Team",
        "budget" => "₹5.40 Cr",
        "spent" => "₹5.40 Cr",
        "progress" => 100,
        "health" => "Completed",
        "healthBadge" => "green",
        "startDate" => "10 Jan 2026",
        "endDate" => "30 Jun 2026",
        "childrenCount" => 0,
        "desc" => "Completed casting for all four floors with M30 concrete grade."
    ],
    [
        "id" => "PRJ-01-SUB1-T2",
        "resortId" => "RES-GOA-01",
        "resortName" => "Grand Oasis Resort & Spa",
        "parentId" => "PRJ-01-SUB1",
        "level" => 3,
        "name" => "External Masonry & Plastering",
        "code" => "GR-CIV-001-A-WP2",
        "discipline" => "Civil Structure",
        "owner" => "Site Team",
        "budget" => "₹3.80 Cr",
        "spent" => "₹2.40 Cr",
        "progress" => 70,
        "health" => "On Track",
        "healthBadge" => "green",
        "startDate" => "01 Jul 2026",
        "endDate" => "15 Oct 2026",
        "childrenCount" => 0,
        "desc" => "AAC block masonry and double coat external sand face plaster."
    ],
    [
        "id" => "PRJ-01-SUB2",
        "resortId" => "RES-GOA-01",
        "resortName" => "Grand Oasis Resort & Spa",
        "parentId" => "PRJ-01",
        "level" => 2,
        "name" => "Block B Luxury Pool Villas Civil Shell",
        "code" => "GR-CIV-001-B",
        "discipline" => "Civil Structure",
        "owner" => "Ravi Shankar",
        "budget" => "₹7.30 Cr",
        "spent" => "₹5.40 Cr",
        "progress" => 74,
        "health" => "On Track",
        "healthBadge" => "green",
        "startDate" => "15 Feb 2026",
        "endDate" => "30 Nov 2026",
        "childrenCount" => 0,
        "desc" => "12 individual duplex villa shells with private plunge pool basins."
    ],
    [
        "id" => "PRJ-02",
        "resortId" => "RES-GOA-01",
        "resortName" => "Grand Oasis Resort & Spa",
        "parentId" => null,
        "level" => 1,
        "name" => "Grand Resort MEP & Automation Infrastructure",
        "code" => "GR-MEP-001",
        "discipline" => "MEP & Electrical",
        "owner" => "Rahul Sharma",
        "budget" => "₹12.40 Cr",
        "spent" => "₹8.90 Cr",
        "progress" => 72,
        "health" => "On Track",
        "healthBadge" => "green",
        "startDate" => "01 Mar 2026",
        "endDate" => "24 Dec 2026",
        "childrenCount" => 3,
        "desc" => "Central electrical distribution, 11kV substation, HVAC chiller plant, plumbing and fire safety network."
    ],
    [
        "id" => "PRJ-02-SUB1",
        "resortId" => "RES-GOA-01",
        "resortName" => "Grand Oasis Resort & Spa",
        "parentId" => "PRJ-02",
        "level" => 2,
        "name" => "Electrical Distribution & 11kV Substation",
        "code" => "GR-MEP-001-ELE",
        "discipline" => "Electrical",
        "owner" => "Rahul Sharma",
        "budget" => "₹5.10 Cr",
        "spent" => "₹4.30 Cr",
        "progress" => 84,
        "health" => "On Track",
        "healthBadge" => "green",
        "startDate" => "01 Mar 2026",
        "endDate" => "15 Oct 2026",
        "childrenCount" => 2,
        "desc" => "HT transformers, DG synchronization panels, busduct risers and floor distribution."
    ],
    [
        "id" => "PRJ-02-SUB1-T1",
        "resortId" => "RES-GOA-01",
        "resortName" => "Grand Oasis Resort & Spa",
        "parentId" => "PRJ-02-SUB1",
        "level" => 3,
        "name" => "11kV Substation & 2x 1500 kVA Transformer Setup",
        "code" => "GR-MEP-001-ELE-T1",
        "discipline" => "Electrical",
        "owner" => "Rahul Sharma",
        "budget" => "₹2.90 Cr",
        "spent" => "₹2.80 Cr",
        "progress" => 95,
        "health" => "Completed",
        "healthBadge" => "green",
        "startDate" => "01 Mar 2026",
        "endDate" => "15 Aug 2026",
        "childrenCount" => 0,
        "desc" => "Substation building ready, transformer energized for dry testing."
    ],
    [
        "id" => "PRJ-02-SUB1-T2",
        "resortId" => "RES-GOA-01",
        "resortName" => "Grand Oasis Resort & Spa",
        "parentId" => "PRJ-02-SUB1",
        "level" => 3,
        "name" => "Main Cable Tray Laying & LT Cabling",
        "code" => "GR-MEP-001-ELE-T2",
        "discipline" => "Electrical",
        "owner" => "Rahul Sharma",
        "budget" => "₹2.20 Cr",
        "spent" => "₹1.50 Cr",
        "progress" => 72,
        "health" => "On Track",
        "healthBadge" => "green",
        "startDate" => "15 Jun 2026",
        "endDate" => "15 Oct 2026",
        "childrenCount" => 0,
        "desc" => "4C x 16 sqmm & 4C x 240 sqmm Polycab XLPE cable laying across main duct shafts."
    ],
    [
        "id" => "PRJ-02-SUB2",
        "resortId" => "RES-GOA-01",
        "resortName" => "Grand Oasis Resort & Spa",
        "parentId" => "PRJ-02",
        "level" => 2,
        "name" => "HVAC Central Chiller & VRV Air Conditioning",
        "code" => "GR-MEP-001-HVAC",
        "discipline" => "HVAC",
        "owner" => "Manoj Joshi",
        "budget" => "₹4.80 Cr",
        "spent" => "₹3.60 Cr",
        "progress" => 65,
        "health" => "At Risk",
        "healthBadge" => "amber",
        "startDate" => "15 Apr 2026",
        "endDate" => "15 Nov 2026",
        "childrenCount" => 0,
        "desc" => "Water-cooled chillers, cooling towers, primary/secondary pumps and VRV indoor units."
    ],
    [
        "id" => "PRJ-03",
        "resortId" => "RES-JAI-02",
        "resortName" => "Royal Heritage Palace & Villas",
        "parentId" => null,
        "level" => 1,
        "name" => "Palace Wing Restoration & Structural Fortification",
        "code" => "JAI-CIV-002",
        "discipline" => "Heritage Civil",
        "owner" => "Priya Mehta",
        "budget" => "₹18.40 Cr",
        "spent" => "₹11.20 Cr",
        "progress" => 58,
        "health" => "On Track",
        "healthBadge" => "green",
        "startDate" => "01 Feb 2026",
        "endDate" => "15 Jan 2027",
        "childrenCount" => 2,
        "desc" => "Structural fortification of 18th century sandstone arches, foundation underpinning, and courtyard stone flooring."
    ],
    [
        "id" => "PRJ-03-SUB1",
        "resortId" => "RES-JAI-02",
        "resortName" => "Royal Heritage Palace & Villas",
        "parentId" => "PRJ-03",
        "level" => 2,
        "name" => "Courtyard Lighting & Architectural Facade Automation",
        "code" => "JAI-CIV-002-A",
        "discipline" => "Lighting & MEP",
        "owner" => "Priya Mehta",
        "budget" => "₹7.80 Cr",
        "spent" => "₹4.50 Cr",
        "progress" => 62,
        "health" => "On Track",
        "healthBadge" => "green",
        "startDate" => "15 Mar 2026",
        "endDate" => "30 Nov 2026",
        "childrenCount" => 0,
        "desc" => "Concealed LED architectural wash lighting, DMX controllers, and ambient courtyard spotlights."
    ],
    [
        "id" => "PRJ-04",
        "resortId" => "RES-MAN-03",
        "resortName" => "Pine Valley Mountain Resort",
        "parentId" => null,
        "level" => 1,
        "name" => "Geothermal Heated Pool & Alpine Spa Complex",
        "code" => "MAN-SPA-001",
        "discipline" => "Civil & MEP",
        "owner" => "Vikram Rao",
        "budget" => "₹9.20 Cr",
        "spent" => "₹4.15 Cr",
        "progress" => 45,
        "health" => "On Track",
        "healthBadge" => "green",
        "startDate" => "10 Apr 2026",
        "endDate" => "15 Nov 2026",
        "childrenCount" => 2,
        "desc" => "Geothermal hot water loop, glass-enclosed infinity pool, and steam thermal suites."
    ],
    [
        "id" => "PRJ-04-SUB1",
        "resortId" => "RES-MAN-03",
        "resortName" => "Pine Valley Mountain Resort",
        "parentId" => "PRJ-04",
        "level" => 2,
        "name" => "Sub-Surface Geothermal Heat Exchangers & Piping",
        "code" => "MAN-SPA-001-GEO",
        "discipline" => "HVAC & Thermal",
        "owner" => "Vikram Rao",
        "budget" => "₹4.60 Cr",
        "spent" => "₹2.80 Cr",
        "progress" => 52,
        "health" => "On Track",
        "healthBadge" => "green",
        "startDate" => "10 Apr 2026",
        "endDate" => "30 Sep 2026",
        "childrenCount" => 0,
        "desc" => "Deep bore ground loops, titanium plate heat exchangers, and insulated pre-cast supply lines."
    ],
    [
        "id" => "PRJ-05",
        "resortId" => "RES-KOV-04",
        "resortName" => "Azure Sands Beach Retreat",
        "parentId" => null,
        "level" => 1,
        "name" => "Solar Microgrid & Energy Storage 250kW",
        "code" => "KOV-SLR-001",
        "discipline" => "Renewable Solar",
        "owner" => "Ananya Nair",
        "budget" => "₹6.50 Cr",
        "spent" => "₹2.30 Cr",
        "progress" => 35,
        "health" => "Delayed",
        "healthBadge" => "red",
        "startDate" => "01 May 2026",
        "endDate" => "28 Feb 2027",
        "childrenCount" => 0,
        "desc" => "Rooftop solar photovoltaic plant, 500kWh lithium battery bank, and grid synchronization."
    ]
];

$steps = [
    ["num" => 1, "name" => "Resort Setup", "url" => "resorts.php", "desc" => "Create & configure master resort properties"],
    ["num" => 2, "name" => "N-Level Projects", "url" => "projects.php", "desc" => "Build parent projects, sub-projects & work packages"],
    ["num" => 3, "name" => "Milestones", "url" => "milestones.php", "desc" => "Set critical gateway milestones and dates"],
    ["num" => 4, "name" => "BOQ & Rates", "url" => "boq.php", "desc" => "Import Excel BOQ, rates & link Item Master"],
    ["num" => 5, "name" => "Budget Baselines", "url" => "budget.php", "desc" => "Allocate cost centers & set 80% RAG limits"],
    ["num" => 6, "name" => "Site Execution", "url" => "daily-report.php", "desc" => "Record daily site logs, progress % & issues"],
    ["num" => 7, "name" => "Inventory & Closure", "url" => "inventory.php", "desc" => "Reconcile leftover material & signed handover"],
    ["num" => 8, "name" => "Governance & Roles", "url" => "users.php", "desc" => "Manage granular roles, permissions & audit trail"]
];
?>
